import os
from dotenv import load_dotenv

load_dotenv()

SNEHITH_API_URL = os.getenv("SNEHITH_API_URL")
SNEHITH_ADMIN_EMAIL = os.getenv("SNEHITH_ADMIN_EMAIL")
SNEHITH_ADMIN_PASSWORD = os.getenv("SNEHITH_ADMIN_PASSWORD")
META_WHATSAPP_ACCESS_TOKEN = os.getenv("META_WHATSAPP_ACCESS_TOKEN")
META_WHATSAPP_PHONE_NUMBER_ID = os.getenv("META_WHATSAPP_PHONE_NUMBER_ID")
META_WHATSAPP_BUSINESS_ACCOUNT_ID = os.getenv("META_WHATSAPP_BUSINESS_ACCOUNT_ID", "4062573757379650")
META_WHATSAPP_TICKET_TEMPLATE_NAME = os.getenv("META_WHATSAPP_TICKET_TEMPLATE_NAME", "snehith_travels_ticket_pdf")

SMTP_HOST = os.getenv("SMTP_HOST")
SMTP_PORT = int(os.getenv("SMTP_PORT", "587"))
SMTP_USERNAME = os.getenv("SMTP_USERNAME") or SNEHITH_ADMIN_EMAIL
SMTP_PASSWORD = os.getenv("SMTP_PASSWORD")
SMTP_FROM_EMAIL = os.getenv("SMTP_FROM_EMAIL") or SMTP_USERNAME

if not SNEHITH_API_URL:
    raise RuntimeError("SNEHITH_API_URL is not configured")

if not SNEHITH_ADMIN_EMAIL:
    raise RuntimeError("SNEHITH_ADMIN_EMAIL is not configured")

if not SNEHITH_ADMIN_PASSWORD:
    raise RuntimeError("SNEHITH_ADMIN_PASSWORD is not configured")
